[package]
name = "opcua-read-client"
version = "0.9.0" # OPCUARustVersion
authors = ["Thomas Jespersen <tj@omnio.net>"]
edition = "2018"

[dependencies]
pico-args="0.3"

[dependencies.opcua]
path = "../../lib"
version = "0.11.0" # OPCUARustVersion
features = ["client", "console-logging"]
