// This file was autogenerated from Opc.Ua.Types.bsd.xml by tools/schema/gen_types.js
// DO NOT EDIT THIS FILE

use std::io::{Read, Write};

use encoding::*;
#[allow(unused_imports)]
use basic_types::*;
use service_types::impls::MessageInfo;
use node_ids::ObjectId;
use service_types::impls::RequestHeader;

/// Cancels an outstanding request.
#[derive(Debug, Clone, PartialEq)]
pub struct CancelRequest {
    pub request_header: RequestHeader,
    pub request_handle: u32,
}

impl MessageInfo for CancelRequest {
    fn object_id(&self) -> ObjectId {
        ObjectId::CancelRequest_Encoding_DefaultBinary
    }
}

impl BinaryEncoder<CancelRequest> for CancelRequest {
    fn byte_len(&self) -> usize {
        let mut size = 0;
        size += self.request_header.byte_len();
        size += self.request_handle.byte_len();
        size
    }

    #[allow(unused_variables)]
    fn encode<S: Write>(&self, stream: &mut S) -> EncodingResult<usize> {
        let mut size = 0;
        size += self.request_header.encode(stream)?;
        size += self.request_handle.encode(stream)?;
        Ok(size)
    }

    #[allow(unused_variables)]
    fn decode<S: Read>(stream: &mut S, decoding_limits: &DecodingLimits) -> EncodingResult<Self> {
        let request_header = RequestHeader::decode(stream, decoding_limits)?;
        let request_handle = u32::decode(stream, decoding_limits)?;
        Ok(CancelRequest {
            request_header,
            request_handle,
        })
    }
}
