// This file was autogenerated from Opc.Ua.Types.bsd.xml by tools/schema/gen_types.js
// DO NOT EDIT THIS FILE

use std::io::{Read, Write};

use encoding::*;
#[allow(unused_imports)]
use basic_types::*;
use service_types::impls::MessageInfo;
use node_ids::ObjectId;
use node_id::NodeId;

/// A request to delete a node to the server address space.
#[derive(Debug, Clone, PartialEq)]
pub struct DeleteNodesItem {
    pub node_id: NodeId,
    pub delete_target_references: Boolean,
}

impl MessageInfo for DeleteNodesItem {
    fn object_id(&self) -> ObjectId {
        ObjectId::DeleteNodesItem_Encoding_DefaultBinary
    }
}

impl BinaryEncoder<DeleteNodesItem> for DeleteNodesItem {
    fn byte_len(&self) -> usize {
        let mut size = 0;
        size += self.node_id.byte_len();
        size += self.delete_target_references.byte_len();
        size
    }

    #[allow(unused_variables)]
    fn encode<S: Write>(&self, stream: &mut S) -> EncodingResult<usize> {
        let mut size = 0;
        size += self.node_id.encode(stream)?;
        size += self.delete_target_references.encode(stream)?;
        Ok(size)
    }

    #[allow(unused_variables)]
    fn decode<S: Read>(stream: &mut S, decoding_limits: &DecodingLimits) -> EncodingResult<Self> {
        let node_id = NodeId::decode(stream, decoding_limits)?;
        let delete_target_references = Boolean::decode(stream, decoding_limits)?;
        Ok(DeleteNodesItem {
            node_id,
            delete_target_references,
        })
    }
}
