// This file was autogenerated from Opc.Ua.Types.bsd.xml by tools/schema/gen_types.js
// DO NOT EDIT THIS FILE

use std::io::{Read, Write};

use crate::encoding::*;
#[allow(unused_imports)]
use crate::basic_types::*;
use crate::service_types::impls::MessageInfo;
use crate::node_ids::ObjectId;
use crate::service_types::impls::RequestHeader;
use crate::service_types::enums::TimestampsToReturn;
use crate::service_types::ReadValueId;

#[derive(Debug, Clone, PartialEq)]
pub struct ReadRequest {
    pub request_header: RequestHeader,
    pub max_age: f64,
    pub timestamps_to_return: TimestampsToReturn,
    pub nodes_to_read: Option<Vec<ReadValueId>>,
}

impl MessageInfo for ReadRequest {
    fn object_id(&self) -> ObjectId {
        ObjectId::ReadRequest_Encoding_DefaultBinary
    }
}

impl BinaryEncoder<ReadRequest> for ReadRequest {
    fn byte_len(&self) -> usize {
        let mut size = 0;
        size += self.request_header.byte_len();
        size += self.max_age.byte_len();
        size += self.timestamps_to_return.byte_len();
        size += byte_len_array(&self.nodes_to_read);
        size
    }

    #[allow(unused_variables)]
    fn encode<S: Write>(&self, stream: &mut S) -> EncodingResult<usize> {
        let mut size = 0;
        size += self.request_header.encode(stream)?;
        size += self.max_age.encode(stream)?;
        size += self.timestamps_to_return.encode(stream)?;
        size += write_array(stream, &self.nodes_to_read)?;
        Ok(size)
    }

    #[allow(unused_variables)]
    fn decode<S: Read>(stream: &mut S, decoding_limits: &DecodingLimits) -> EncodingResult<Self> {
        let request_header = RequestHeader::decode(stream, decoding_limits)?;
        let max_age = f64::decode(stream, decoding_limits)?;
        let timestamps_to_return = TimestampsToReturn::decode(stream, decoding_limits)?;
        let nodes_to_read: Option<Vec<ReadValueId>> = read_array(stream, decoding_limits)?;
        Ok(ReadRequest {
            request_header,
            max_age,
            timestamps_to_return,
            nodes_to_read,
        })
    }
}
