// This file was autogenerated from Opc.Ua.Types.bsd.xml by tools/schema/gen_types.js
// DO NOT EDIT THIS FILE

use std::io::{Read, Write};

use crate::encoding::*;
#[allow(unused_imports)]
use crate::basic_types::*;
use crate::service_types::impls::MessageInfo;
use crate::node_ids::ObjectId;
use crate::service_types::impls::RequestHeader;

#[derive(Debug, Clone, PartialEq)]
pub struct RepublishRequest {
    pub request_header: RequestHeader,
    pub subscription_id: u32,
    pub retransmit_sequence_number: u32,
}

impl MessageInfo for RepublishRequest {
    fn object_id(&self) -> ObjectId {
        ObjectId::RepublishRequest_Encoding_DefaultBinary
    }
}

impl BinaryEncoder<RepublishRequest> for RepublishRequest {
    fn byte_len(&self) -> usize {
        let mut size = 0;
        size += self.request_header.byte_len();
        size += self.subscription_id.byte_len();
        size += self.retransmit_sequence_number.byte_len();
        size
    }

    #[allow(unused_variables)]
    fn encode<S: Write>(&self, stream: &mut S) -> EncodingResult<usize> {
        let mut size = 0;
        size += self.request_header.encode(stream)?;
        size += self.subscription_id.encode(stream)?;
        size += self.retransmit_sequence_number.encode(stream)?;
        Ok(size)
    }

    #[allow(unused_variables)]
    fn decode<S: Read>(stream: &mut S, decoding_limits: &DecodingLimits) -> EncodingResult<Self> {
        let request_header = RequestHeader::decode(stream, decoding_limits)?;
        let subscription_id = u32::decode(stream, decoding_limits)?;
        let retransmit_sequence_number = u32::decode(stream, decoding_limits)?;
        Ok(RepublishRequest {
            request_header,
            subscription_id,
            retransmit_sequence_number,
        })
    }
}
