// This file was autogenerated from Opc.Ua.Types.bsd.xml by tools/schema/gen_types.js
// DO NOT EDIT THIS FILE

use std::io::{Read, Write};

use encoding::*;
#[allow(unused_imports)]
use basic_types::*;
use service_types::impls::MessageInfo;
use node_ids::ObjectId;
use service_types::impls::ResponseHeader;
use service_types::NotificationMessage;

#[derive(Debug, Clone, PartialEq)]
pub struct RepublishResponse {
    pub response_header: ResponseHeader,
    pub notification_message: NotificationMessage,
}

impl MessageInfo for RepublishResponse {
    fn object_id(&self) -> ObjectId {
        ObjectId::RepublishResponse_Encoding_DefaultBinary
    }
}

impl BinaryEncoder<RepublishResponse> for RepublishResponse {
    fn byte_len(&self) -> usize {
        let mut size = 0;
        size += self.response_header.byte_len();
        size += self.notification_message.byte_len();
        size
    }

    #[allow(unused_variables)]
    fn encode<S: Write>(&self, stream: &mut S) -> EncodingResult<usize> {
        let mut size = 0;
        size += self.response_header.encode(stream)?;
        size += self.notification_message.encode(stream)?;
        Ok(size)
    }

    #[allow(unused_variables)]
    fn decode<S: Read>(stream: &mut S) -> EncodingResult<Self> {
        let response_header = ResponseHeader::decode(stream)?;
        let notification_message = NotificationMessage::decode(stream)?;
        Ok(RepublishResponse {
            response_header,
            notification_message,
        })
    }
}
