[package]
name = "opcua-discovery-client"
authors = ["Adam Lock <locka99@gmail.com>"]

version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
env_logger = "0.10.1"
opcua-client = { version = "0.12.0", path = "../../crates/client" }
pico-args = "0.5"
