[package]
name = "opcua-chess-server"
authors = ["Adam Lock <locka99@gmail.com>"]

version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
opcua-server = { version = "0.12.0", path = "../../crates/server" }
parking_lot = "0.12.1"
uci = "0.1.3"
