[package]
name = "opcua-chess-server"
authors = ["Adam Lock <locka99@gmail.com>"]

version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
uci = "0.1.3"

[dependencies.opcua]
path = "../../lib"
features = ["server", "console-logging"]
