var _ = require("lodash");
var csv = require("csv-parser");
var fs = require("fs");

var settings = require("./settings");

var status_code_csv = `${settings.schema_dir}/NodeIds.csv`;

var rs_out = fs.createWriteStream(`${settings.rs_dir}/types/node_ids.rs`);

function write_to_rs(out, message) {
    out.write(message);
}

write_to_rs(rs_out, `// This file was autogenerated from NodeIds.csv\n`);

var node_ids = { };

var csv_data = fs.createReadStream(status_code_csv)
    .pipe(csv(['name', 'id', 'type']))
    .on('data', function (data) {
        var node = {
            name: data.name,
            id: data.id
        };
        if (_.has(node_ids, data.type)) {
            node_ids[data.type].push(node);
        }
        else {
            node_ids[data.type] = [ node ];
        }
    })
    .on('end', function () {
        _.each(node_ids, function(value, key) {
             write_to_rs(rs_out, 
`
#[allow(non_camel_case_types)]
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum ${key}Id {
`);
            _.each(value, function (node) {
                write_to_rs(rs_out, `    ${node.name} = ${node.id},\n`);
            });
            write_to_rs(rs_out, `}\n`);

            write_to_rs(rs_out, `
impl ${key}Id {
    pub fn from_u64(value: u64) -> Result<${key}Id, ()> {
        match value {
`);
            _.each(value, function (node) {
                write_to_rs(rs_out, `            ${node.id} => Ok(${key}Id::${node.name}),\n`);
            });

            write_to_rs(rs_out,
`            _ => Err(())
        }
    }
}
`);

        });
    });

