let _ = require("lodash");
let fs = require("fs");
let xml2js = require("xml2js");

let nodeset = require("./nodeset");

// gen_nodeset.js is a generalized nodeset parser / generator.

let argv = require("yargs")
    .usage("Usage: $0 --nodeset [path] --module [name] --outputdir [path] --opcua_server_crate [bool]")
    .demandOption(['nodeset', 'module'])
    .describe('nodeset', "The OPC UA XML node set to parse")
    .describe('module', "The Rust module to generate into, e.g. foo will create a file called foo.rs")
    .describe('outputdir', "The directory to generate Rust modules into")
    .default('outputdir', ".")
    .describe('ns', "Rewrites any non-zero namespace index to this new value")
    .boolean('opcua_server_crate')
    .describe('opcua_server_crate', "Whether the generated module is to be used internally by opcua_server crate")
    .default('opcua_server_crate', true)
    .argv;

let xml_file = argv.nodeset;
let rs_module = argv.module;
let namespace_index = argv.ns ? argv.ns : -1;
let opcua_server_crate = argv.opcua_server_crate;


let trace = false;
let config = {
    destination_dir: argv.outputdir,
    autogenerated_by: "tools/schema/gen_nodeset.js",
    trace: trace,
    namespace_index: namespace_index,
    opcua_server_crate: opcua_server_crate,
    copyright: false
}

nodeset.from_xml(xml_file, rs_module, config);