[package]
name = "opcua-mqtt-client"
authors = ["Adam Lock <locka99@gmail.com>"]

version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
pico-args = "0.5"
rumqttc = "0.17.0"

[dependencies.opcua]
path = "../../lib"
features = ["client", "console-logging"]
