name: CI verify cleanly generated status codes
'on':
  workflow_call: null
jobs:
  status_codes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
        working-directory: tools/schema/
      - name: Regenerate status codes
        run: node gen_status_codes
        working-directory: tools/schema/
      - name: Format generated code
        run: rustfmt lib/src/types/status_codes.rs
      - name: Verify generated code matches committed code
        run: git status --porcelain
